version: "3"

services:
  db:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQLDB_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /Users/junseok/datadir:/var/lib/mysql
